package in.elanic.elanicchatdemo.models.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import in.elanic.elanicchatdemo.models.db.User;
import in.elanic.elanicchatdemo.models.db.Product;
import in.elanic.elanicchatdemo.models.db.Message;
import in.elanic.elanicchatdemo.models.db.ChatItem;
import in.elanic.elanicchatdemo.models.db.WSRequest;

import in.elanic.elanicchatdemo.models.db.UserDao;
import in.elanic.elanicchatdemo.models.db.ProductDao;
import in.elanic.elanicchatdemo.models.db.MessageDao;
import in.elanic.elanicchatdemo.models.db.ChatItemDao;
import in.elanic.elanicchatdemo.models.db.WSRequestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig chatItemDaoConfig;
    private final DaoConfig wSRequestDaoConfig;

    private final UserDao userDao;
    private final ProductDao productDao;
    private final MessageDao messageDao;
    private final ChatItemDao chatItemDao;
    private final WSRequestDao wSRequestDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        chatItemDaoConfig = daoConfigMap.get(ChatItemDao.class).clone();
        chatItemDaoConfig.initIdentityScope(type);

        wSRequestDaoConfig = daoConfigMap.get(WSRequestDao.class).clone();
        wSRequestDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        chatItemDao = new ChatItemDao(chatItemDaoConfig, this);
        wSRequestDao = new WSRequestDao(wSRequestDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Product.class, productDao);
        registerDao(Message.class, messageDao);
        registerDao(ChatItem.class, chatItemDao);
        registerDao(WSRequest.class, wSRequestDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
        chatItemDaoConfig.getIdentityScope().clear();
        wSRequestDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public ChatItemDao getChatItemDao() {
        return chatItemDao;
    }

    public WSRequestDao getWSRequestDao() {
        return wSRequestDao;
    }

}
