package in.elanic.elanicchatdemo.models.db;

import in.elanic.elanicchatdemo.models.db.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE".
 */
public class Message {

    private String message_id;
    private String local_id;
    private String type;
    private String content;
    private String product_id;
    private String buyer_id;
    private String seller_id;
    private String sender_id;
    private Integer offer_price;
    private String offer_status;
    private Integer validity;
    private String offer_earning_data;
    private java.util.Date created_at;
    private java.util.Date updated_at;
    private java.util.Date delivered_at;
    private java.util.Date read_at;
    private Boolean is_read;
    private Boolean is_deleted;
    private String offer_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MessageDao myDao;

    private Product product;
    private String product__resolvedKey;

    private User buyer;
    private String buyer__resolvedKey;

    private User seller;
    private String seller__resolvedKey;

    private User sender;
    private String sender__resolvedKey;


    public Message() {
    }

    public Message(String message_id) {
        this.message_id = message_id;
    }

    public Message(String message_id, String local_id, String type, String content, String product_id, String buyer_id, String seller_id, String sender_id, Integer offer_price, String offer_status, Integer validity, String offer_earning_data, java.util.Date created_at, java.util.Date updated_at, java.util.Date delivered_at, java.util.Date read_at, Boolean is_read, Boolean is_deleted, String offer_id) {
        this.message_id = message_id;
        this.local_id = local_id;
        this.type = type;
        this.content = content;
        this.product_id = product_id;
        this.buyer_id = buyer_id;
        this.seller_id = seller_id;
        this.sender_id = sender_id;
        this.offer_price = offer_price;
        this.offer_status = offer_status;
        this.validity = validity;
        this.offer_earning_data = offer_earning_data;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.delivered_at = delivered_at;
        this.read_at = read_at;
        this.is_read = is_read;
        this.is_deleted = is_deleted;
        this.offer_id = offer_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMessageDao() : null;
    }

    public String getMessage_id() {
        return message_id;
    }

    public void setMessage_id(String message_id) {
        this.message_id = message_id;
    }

    public String getLocal_id() {
        return local_id;
    }

    public void setLocal_id(String local_id) {
        this.local_id = local_id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getProduct_id() {
        return product_id;
    }

    public void setProduct_id(String product_id) {
        this.product_id = product_id;
    }

    public String getBuyer_id() {
        return buyer_id;
    }

    public void setBuyer_id(String buyer_id) {
        this.buyer_id = buyer_id;
    }

    public String getSeller_id() {
        return seller_id;
    }

    public void setSeller_id(String seller_id) {
        this.seller_id = seller_id;
    }

    public String getSender_id() {
        return sender_id;
    }

    public void setSender_id(String sender_id) {
        this.sender_id = sender_id;
    }

    public Integer getOffer_price() {
        return offer_price;
    }

    public void setOffer_price(Integer offer_price) {
        this.offer_price = offer_price;
    }

    public String getOffer_status() {
        return offer_status;
    }

    public void setOffer_status(String offer_status) {
        this.offer_status = offer_status;
    }

    public Integer getValidity() {
        return validity;
    }

    public void setValidity(Integer validity) {
        this.validity = validity;
    }

    public String getOffer_earning_data() {
        return offer_earning_data;
    }

    public void setOffer_earning_data(String offer_earning_data) {
        this.offer_earning_data = offer_earning_data;
    }

    public java.util.Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(java.util.Date created_at) {
        this.created_at = created_at;
    }

    public java.util.Date getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(java.util.Date updated_at) {
        this.updated_at = updated_at;
    }

    public java.util.Date getDelivered_at() {
        return delivered_at;
    }

    public void setDelivered_at(java.util.Date delivered_at) {
        this.delivered_at = delivered_at;
    }

    public java.util.Date getRead_at() {
        return read_at;
    }

    public void setRead_at(java.util.Date read_at) {
        this.read_at = read_at;
    }

    public Boolean getIs_read() {
        return is_read;
    }

    public void setIs_read(Boolean is_read) {
        this.is_read = is_read;
    }

    public Boolean getIs_deleted() {
        return is_deleted;
    }

    public void setIs_deleted(Boolean is_deleted) {
        this.is_deleted = is_deleted;
    }

    public String getOffer_id() {
        return offer_id;
    }

    public void setOffer_id(String offer_id) {
        this.offer_id = offer_id;
    }

    /** To-one relationship, resolved on first access. */
    public Product getProduct() {
        String __key = this.product_id;
        if (product__resolvedKey == null || product__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ProductDao targetDao = daoSession.getProductDao();
            Product productNew = targetDao.load(__key);
            synchronized (this) {
                product = productNew;
            	product__resolvedKey = __key;
            }
        }
        return product;
    }

    public void setProduct(Product product) {
        synchronized (this) {
            this.product = product;
            product_id = product == null ? null : product.getProduct_id();
            product__resolvedKey = product_id;
        }
    }

    /** To-one relationship, resolved on first access. */
    public User getBuyer() {
        String __key = this.buyer_id;
        if (buyer__resolvedKey == null || buyer__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserDao targetDao = daoSession.getUserDao();
            User buyerNew = targetDao.load(__key);
            synchronized (this) {
                buyer = buyerNew;
            	buyer__resolvedKey = __key;
            }
        }
        return buyer;
    }

    public void setBuyer(User buyer) {
        synchronized (this) {
            this.buyer = buyer;
            buyer_id = buyer == null ? null : buyer.getUser_id();
            buyer__resolvedKey = buyer_id;
        }
    }

    /** To-one relationship, resolved on first access. */
    public User getSeller() {
        String __key = this.seller_id;
        if (seller__resolvedKey == null || seller__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserDao targetDao = daoSession.getUserDao();
            User sellerNew = targetDao.load(__key);
            synchronized (this) {
                seller = sellerNew;
            	seller__resolvedKey = __key;
            }
        }
        return seller;
    }

    public void setSeller(User seller) {
        synchronized (this) {
            this.seller = seller;
            seller_id = seller == null ? null : seller.getUser_id();
            seller__resolvedKey = seller_id;
        }
    }

    /** To-one relationship, resolved on first access. */
    public User getSender() {
        String __key = this.sender_id;
        if (sender__resolvedKey == null || sender__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserDao targetDao = daoSession.getUserDao();
            User senderNew = targetDao.load(__key);
            synchronized (this) {
                sender = senderNew;
            	sender__resolvedKey = __key;
            }
        }
        return sender;
    }

    public void setSender(User sender) {
        synchronized (this) {
            this.sender = sender;
            sender_id = sender == null ? null : sender.getUser_id();
            sender__resolvedKey = sender_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
