package in.elanic.elanicchatdemo.models.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import in.elanic.elanicchatdemo.models.db.WSRequest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WSREQUEST".
*/
public class WSRequestDao extends AbstractDao<WSRequest, String> {

    public static final String TABLENAME = "WSREQUEST";

    /**
     * Properties of entity WSRequest.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Request_id = new Property(0, String.class, "request_id", true, "REQUEST_ID");
        public final static Property User_id = new Property(1, String.class, "user_id", false, "USER_ID");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property Is_completed = new Property(3, Boolean.class, "is_completed", false, "IS_COMPLETED");
        public final static Property Created_at = new Property(4, java.util.Date.class, "created_at", false, "CREATED_AT");
        public final static Property Updated_at = new Property(5, java.util.Date.class, "updated_at", false, "UPDATED_AT");
        public final static Property Is_deleted = new Property(6, Boolean.class, "is_deleted", false, "IS_DELETED");
        public final static Property Event_name = new Property(7, String.class, "event_name", false, "EVENT_NAME");
    };


    public WSRequestDao(DaoConfig config) {
        super(config);
    }
    
    public WSRequestDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WSREQUEST\" (" + //
                "\"REQUEST_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: request_id
                "\"USER_ID\" TEXT," + // 1: user_id
                "\"CONTENT\" TEXT," + // 2: content
                "\"IS_COMPLETED\" INTEGER," + // 3: is_completed
                "\"CREATED_AT\" INTEGER," + // 4: created_at
                "\"UPDATED_AT\" INTEGER," + // 5: updated_at
                "\"IS_DELETED\" INTEGER," + // 6: is_deleted
                "\"EVENT_NAME\" TEXT);"); // 7: event_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WSREQUEST\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, WSRequest entity) {
        stmt.clearBindings();
 
        String request_id = entity.getRequest_id();
        if (request_id != null) {
            stmt.bindString(1, request_id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(2, user_id);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
 
        Boolean is_completed = entity.getIs_completed();
        if (is_completed != null) {
            stmt.bindLong(4, is_completed ? 1L: 0L);
        }
 
        java.util.Date created_at = entity.getCreated_at();
        if (created_at != null) {
            stmt.bindLong(5, created_at.getTime());
        }
 
        java.util.Date updated_at = entity.getUpdated_at();
        if (updated_at != null) {
            stmt.bindLong(6, updated_at.getTime());
        }
 
        Boolean is_deleted = entity.getIs_deleted();
        if (is_deleted != null) {
            stmt.bindLong(7, is_deleted ? 1L: 0L);
        }
 
        String event_name = entity.getEvent_name();
        if (event_name != null) {
            stmt.bindString(8, event_name);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public WSRequest readEntity(Cursor cursor, int offset) {
        WSRequest entity = new WSRequest( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // request_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // user_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // content
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // is_completed
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // created_at
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // updated_at
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // is_deleted
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // event_name
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, WSRequest entity, int offset) {
        entity.setRequest_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUser_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIs_completed(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setCreated_at(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setUpdated_at(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setIs_deleted(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setEvent_name(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(WSRequest entity, long rowId) {
        return entity.getRequest_id();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(WSRequest entity) {
        if(entity != null) {
            return entity.getRequest_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
